-- USERS
INSERT INTO USERS (CREATED_AT, EMAIL, ENABLED, ENCODED_PASSWORD, FIRST_NAME, LAST_NAME)
VALUES
    (CURRENT_TIMESTAMP, 'john@test.com', TRUE,
     '$2a$10$7QJ9e5K1s6gk3uXyJ9u8k.6f0h1c9T0mE1FvJ7sG9vY1n3qT5u6k2',
     'John', 'Advertiser');

INSERT INTO USERS (CREATED_AT, EMAIL, ENABLED, ENCODED_PASSWORD, FIRST_NAME, LAST_NAME)
VALUES
    (CURRENT_TIMESTAMP, 'alice@test.com', TRUE,
     '$2a$10$7QJ9e5K1s6gk3uXyJ9u8k.6f0h1c9T0mE1FvJ7sG9vY1n3qT5u6k2',
     'Alice', 'Advertiser');

INSERT INTO USER_ROLES (USER_ID, SYSTEM_ROLES)
VALUES
    (1,'ACCOUNT_OWNER'),
    (2,'ACCOUNT_OWNER');