server:
  port: ${PORT:8082}

spring:
  application:
    name: campaign-service

  datasource:
    url: jdbc:h2:mem:campaigndb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://discovery-service.onrender.com/eureka
  instance:
    prefer-ip-address: false