server:
  port: ${PORT:8082}

spring:
  application:
    name: campaign-service

  datasource:
    url: jdbc:h2:mem:campaigndb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://campaign-manager-platform.onrender.com/eureka
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30