server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

      routes:

        - id: user-security
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: company
          uri: lb://CAMPAIGN-SERVICE
          predicates:
            - Path=/company/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka